# Generated by Django 5.2 on 2025-08-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='show_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appeal',
            name='show_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appeal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
