# Generated by Django 5.2 on 2025-08-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_appeal_answer_appeal_show_expert_appeal_show_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='appeals/'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
