# Generated by Django 5.2 on 2025-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0003_appeal_message_file_alter_appeal_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('year', models.IntegerField(verbose_name='Yil')),
            ],
        ),
    ]
