# Generated by Django 5.2 on 2025-08-04 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0004_appealconditions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='show_student',
        ),
        migrations.CreateModel(
            name='AnswerToAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('show_student', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='appeal.appeal')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
