# Generated by Django 5.2 on 2025-08-04 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0005_remove_appeal_answer_remove_appeal_show_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertoappeal',
            name='appeal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='appeal.appeal'),
        ),
    ]
