# Generated by Django 5.2 on 2025-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0006_alter_answertoappeal_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertoappeal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
