# Generated by Django 5.2 on 2025-06-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, unique=True, verbose_name="To'liq ism sharifi"),
        ),
    ]
