# Generated by Django 5.2 on 2025-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Yashash manzili'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=200, unique=True, verbose_name="To'liq ism sharifi"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('training', 'Training'), ('spirituality', 'Spirituality'), ('special', 'Special')], max_length=30),
        ),
    ]
