# Generated by Django 5.2 on 2025-05-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('training', 'Training'), ('spirituality', 'Spirituality'), ('special', 'Special')], max_length=20),
        ),
    ]
