# Generated by Django 5.2 on 2025-05-26 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depfin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depfin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depone',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deptwo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deptow', to=settings.AUTH_USER_MODEL),
        ),
    ]
