# Generated by Django 5.2 on 2025-05-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_education_direction', models.CharField(max_length=20, verbose_name="Ta'lim yo'nalishi")),
                ('student_privilege_category', models.CharField(max_length=20, verbose_name='Imtiyozlar toifasi')),
                ('student_education_level', models.CharField(max_length=20, verbose_name="Ta'lim darajasi")),
                ('application_status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=10, verbose_name='Ariza holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
