# Generated by Django 5.2 on 2025-05-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=15)),
                ('student_address', models.TextField()),
                ('student_gpa', models.DecimalField(decimal_places=1, max_digits=2)),
                ('student_education_direction', models.CharField(choices=[('undefined', 'Undefined'), ('science', 'Science'), ('engineering', 'Engineering'), ('arts', 'Arts'), ('business', 'Business'), ('medicine', 'Medicine')], default='undefined', max_length=20)),
                ('student_privilege_category', models.CharField(choices=[('undefined', 'Undefined'), ('student', 'Student'), ('employee', 'Employee'), ('admin', 'Admin')], default='undefined', max_length=20)),
                ('student_education_level', models.CharField(choices=[('undefined', 'Undefined'), ('high_school', 'High School'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('doctorate', 'Doctorate')], default='undefined', max_length=20)),
                ('application_status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_id'], name='application_student_4f98fa_idx'), models.Index(fields=['student_name'], name='application_student_1c2d53_idx'), models.Index(fields=['student_phone'], name='application_student_672b0e_idx'), models.Index(fields=['student_education_direction'], name='application_student_6b6819_idx'), models.Index(fields=['student_privilege_category'], name='application_student_ef9e68_idx'), models.Index(fields=['student_education_level'], name='application_student_25f47a_idx'), models.Index(fields=['application_status'], name='application_applica_5281c4_idx'), models.Index(fields=['created_at'], name='application_created_c1325c_idx')],
            },
        ),
    ]
