# Generated by Django 5.2 on 2025-05-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='student.student'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student_education_direction'], name='application_student_6b6819_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student_privilege_category'], name='application_student_ef9e68_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student_education_level'], name='application_student_25f47a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_status'], name='application_applica_5281c4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c1325c_idx'),
        ),
    ]
