# Generated by Django 5.2 on 2025-05-26 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='student.student'),
        ),
        migrations.AddField(
            model_name='ballapplication',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='application.application'),
        ),
        migrations.AddField(
            model_name='ballapplication',
            name='ball_spirituality',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spirituality', to='application.spiritualityball'),
        ),
        migrations.AddField(
            model_name='ballapplication',
            name='ball_training',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training', to='application.trainingball'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_status'], name='application_applica_5281c4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c1325c_idx'),
        ),
    ]
