# Generated by Django 5.2 on 2025-05-28 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyApplicationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('course', models.IntegerField(help_text='Nechanchi kurslar uchun ochilgan (1, 2, ...)')),
                ('min_gpa', models.DecimalField(decimal_places=1, default=3.5, help_text='Talabaning minimal GPA balli (0.0 - 5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Minimal GPA')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
