# Generated by Django 5.2 on 2025-05-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_student'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='application_student_6b6819_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='application_student_ef9e68_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='application_student_25f47a_idx',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student_education_direction',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student_education_level',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student_privilege_category',
        ),
    ]
