# Generated by Django 5.2 on 2025-06-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_yearlyapplicationwindow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterModelOptions(
            name='ballapplication',
            options={'verbose_name': "Ariza bo'yicha ball", 'verbose_name_plural': "Arizalar bo'yicha ballar"},
        ),
        migrations.AlterModelOptions(
            name='spiritualityball',
            options={'verbose_name': "Ijtimoiy faollik qo'ygan bal", 'verbose_name_plural': "Ijtimoiy faollik qo'ygan ballar"},
        ),
        migrations.AlterModelOptions(
            name='trainingball',
            options={'verbose_name': "Akademik o'zlashtirish bo'yicha ball", 'verbose_name_plural': "Akademik o'zlashtirish bo'yicha ballar"},
        ),
        migrations.AlterModelOptions(
            name='yearlyapplicationwindow',
            options={'verbose_name': 'Ariza topshirish uchun shart', 'verbose_name_plural': 'Ariza topshirish uchun shartlar'},
        ),
    ]
