# Generated by Django 5.2 on 2025-06-26 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiritualityball',
            name='field11',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name="Manaviy-ma'rifiy sohaga oid boshqa yo'nalishlardagi faoligi (0-5)"),
        ),
    ]
