# Generated by Django 5.2 on 2025-05-21 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_application_application_student_6b6819_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiritualityBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.DecimalField(decimal_places=1, max_digits=3)),
                ('field2', models.DecimalField(decimal_places=1, max_digits=3)),
                ('field3', models.DecimalField(decimal_places=1, max_digits=3)),
                ('field4', models.DecimalField(decimal_places=1, max_digits=3)),
                ('field5', models.DecimalField(decimal_places=1, max_digits=3)),
                ('field6', models.DecimalField(decimal_places=1, max_digits=3)),
                ('field7', models.DecimalField(decimal_places=1, max_digits=3)),
                ('field8', models.DecimalField(decimal_places=1, max_digits=3)),
                ('field9', models.DecimalField(decimal_places=1, max_digits=3)),
                ('field10', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='BallApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='application.application')),
                ('ball_spirituality', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spirituality', to='application.spiritualityball')),
                ('ball_training', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training', to='application.trainingball')),
            ],
        ),
    ]
