# Generated by Django 5.2 on 2025-06-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_application_academic_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingball',
            name='field',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name="Talabaning o'zlshtirish ko'rsatkichi"),
        ),
    ]
