# Generated by Django 5.2 on 2025-08-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_spiritualityball_field1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cultural_visits',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Teatr va muzey, xiyobon, kino, tarixiy qadamjolarga tashriflar (0-5)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='enlightenment_classes',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Talabaning "Ma\'rifat darslari"dagi faol ishtirok (0-10)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='participation_in_events',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name="Xalqaro, respublika, viloyat miqyosidagi ko'rik-tanlov, fan olimpiadalari va sport musobaqalarida erishgan natijalari (0-10)"),
        ),
        migrations.AlterField(
            model_name='application',
            name='spiritual_enlightenment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name="Ma'naviy-ma'rifiy sohaga oid boshqa yo'nalishlardagi faoliyati (0-5)"),
        ),
        migrations.AlterField(
            model_name='application',
            name='sports_activity',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Talabalarning sport bilan shug‘ullanishi va sog‘lom turmush tarziga amal qilishi (0-5)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='volunteer_work',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Volontyorlik va jamoat ishlaridagi faolligi (0-5)'),
        ),
    ]
