# Generated by Django 5.2 on 2025-05-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_number', models.CharField(max_length=15, verbose_name='Student ID')),
                ('image', models.ImageField(upload_to='downloads/', verbose_name='Student rasmi')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Pasport raqami')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Student GPA')),
                ('specialty', models.CharField(max_length=100, verbose_name='Mutaxasislik')),
                ('studentStatus', models.CharField(max_length=20, verbose_name='Talaba xolati')),
                ('educationForm', models.CharField(max_length=50, verbose_name="O'quv formati")),
                ('educationType', models.CharField(max_length=50, verbose_name="O'qish turi")),
                ('paymentForm', models.CharField(max_length=50, verbose_name="To'lov xolati")),
                ('group', models.CharField(max_length=50, verbose_name='Talaba gruh nomi')),
                ('educationLang', models.CharField(max_length=50, verbose_name="O'qish tili")),
                ('faculty', models.CharField(max_length=50, verbose_name='Fakultet')),
                ('localityType', models.CharField(max_length=50, verbose_name='Hudud')),
                ('level', models.CharField(max_length=50, verbose_name='Bosqich talabasi')),
                ('semester', models.CharField(max_length=50, verbose_name='Semestr')),
                ('education_year', models.CharField(max_length=20, verbose_name="O'quv yili")),
                ('province', models.CharField(max_length=50, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=50, verbose_name='Tuman')),
                ('accommodation', models.CharField(max_length=50, verbose_name='Turar joyi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student',
                'ordering': ['-created_at'],
            },
        ),
    ]
