# Generated by Django 5.2 on 2025-06-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='educationForm',
            field=models.CharField(max_length=100, verbose_name="O'quv formati"),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=200, verbose_name='Talaba gruh nomi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=100, verbose_name='Bosqich talabasi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='localityType',
            field=models.CharField(max_length=100, verbose_name='Hudud'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=100, verbose_name='Semestr'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentStatus',
            field=models.CharField(max_length=100, verbose_name='Talaba xolati'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id_number',
            field=models.CharField(max_length=20, verbose_name='Student ID'),
        ),
    ]
