# Generated by Django 5.2 on 2025-05-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='district',
        ),
        migrations.RemoveField(
            model_name='student',
            name='educationLang',
        ),
        migrations.RemoveField(
            model_name='student',
            name='educationType',
        ),
        migrations.RemoveField(
            model_name='student',
            name='education_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paymentForm',
        ),
        migrations.RemoveField(
            model_name='student',
            name='province',
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
