# Generated by Django 5.2 on 2025-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_educationform_alter_student_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='educationForm',
            field=models.CharField(max_length=200, verbose_name="O'quv formati"),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=200, verbose_name='Bosqich talabasi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='localityType',
            field=models.CharField(max_length=200, verbose_name='Hudud'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=200, verbose_name='Semestr'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.CharField(max_length=200, verbose_name='Mutaxasislik'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentStatus',
            field=models.CharField(max_length=200, verbose_name='Talaba xolati'),
        ),
    ]
